### ISSUE TITLE
feature request: send to kindle

### ISSUE THREAD

**Issue by bbelderbos** [igbt6/Packt-Publishing-Free-Learning#15]
thanks for this awesome script!

what would be very cool is the send to kindle option, I use that a lot myself when I enter the daily deal. maybe I can look at implementing it myself, just wanted to know if you have thought about adding it.

**Comment by igbt6** [comment]
Hello buddy! nice idea! i have not played with any Kindle API so far, so if you have some experience with that or mostly have some fre time to add such feature, feel free and welcome : )

**Comment by bbelderbos** [comment]
thank you, in packt you can add your send-to-kindle email and packt shows a button, if time this weekend, will give it a try ...

**Comment by bbelderbos** [comment]
no need to scrape the page further, you can just add a mail attachment option that sends pdf to mail and mobi to kindle (which combo I find ideal). 

method from here: http://stackoverflow.com/questions/3362600/how-to-send-email-attachments-with-python 

got it working, but need to clean it up a bit so we set all 3 emails (from, pdf-to, kindle-to) in config file, will do pull request when I have it ...

**Comment by bbelderbos** [comment]
email working, kindle not. opened pull requests, maybe you can check it and let me know if this is useful. cheers
