### ISSUE TITLE
feature request: specify logfile (for logging output)

### ISSUE THREAD

**Issue by bbelderbos** [igbt6/Packt-Publishing-Free-Learning#16]
Hi again, practical thing ... it seems that the standard log option writes this to the specified logfile (in config): 

TITLE --> Python Unlocked
DESCRIPTION --> Become more fluent in Python—learn strategies and techniques for smart and high-performance Python programming
AUTHOR --> Arun Tigeraniya
TIME --> 2015-12-30
DOWNLOADED_AT --> 15-10-2016 02:21

the logging module output however is more verbose / useful info, but goes to console only:
 
[INFO] - Creating session...                                                                                                                                                  
[INFO] - Session created, logged in successfully!
[INFO] - Start grabbing eBook...
..
..

So when using this script I added "filename=.. " to the basicConfig of logging: 

logging.basicConfig(format='[%(levelname)s] - %(message)s', **filename='logfile.log',** level=logging.INFO)                                                                       

Maybe this can be feature can be added to config / cli switches? I found it not that straight-forward though as this happens at the toplevel of the module, yet the reading of config variables happens in the PacktAccountData class. 

thanks

**Comment by bbelderbos** [comment]
related to this is the regular log write option which is coupled with the -g option only: 

    parser.add_argument("-gl", "--grabl", help="grabs and log data",
                        action="store_true")

was that a conscious choice? I would offer logging with each cli option

kudos for this project, I was going to roll my own but this solution works very well, thanks

**Comment by igbt6** [comment]
"was that a conscious choice ?"  - yeah that's a good question :D; first idea was that when you only claim a book without downloading, you'd like to know what has been claimed to download or not it later, taht's why you log it, when you also download it, you already automatically know what has been retrieved. But yes, you're totally right, it should be available as an extra option for each option sepeartaely, When i only find  some time to extend it, i'll do it !

**Comment by igbt6** [comment]
done, take a look at LOG_FILE_PATH in utils/logger.py  , Separeted logging to file and console,
