### ISSUE TITLE
videos

### ISSUE THREAD

**Issue by jaan143** [igbt6/Packt-Publishing-Free-Learning#18]
hi
first of all thanks for making this program
can you tell me we can download packt publishing videos also from this downloader ?

**Comment by igbt6** [comment]
Hi, 
good you found it useful.
Actually there is no such feature implemented, i didn't buy any videos from packt so could not even test it :)   You can open pull request and try to add the feature on your own, it shouldn't be too difficult. In case f any problems, feel free to ask.

Best regards !
