### ISSUE TITLE
Seems like hanged on big downloads

### ISSUE THREAD

**Issue by nevzat** [igbt6/Packt-Publishing-Free-Learning#19]
Download seems hanged or timeout when a big file downloads e.g. last weeks "Blender 2.5 Materials and Textures Cookbook" title's code file which was a couple of hundredths MB in size! I waited for hours for it to complete, there was no disk activity for a long time so I finally pressed Ctrl-C to end the script. Luckily the file was fully downloaded but somehow script hanged there. After my Ctrl-C, the script continued processing other files. I think there should be a progress indicator for displaying how much of a file is downloaded, either a percentage or raw bytes.

**Comment by igbt6** [comment]
Hello, i haven't observed such behavior so far, i'll try to check this and fix, progress status bar, would be good, when i only find some more free time, i'll add it.

**Comment by trancen** [comment]
I can confirm the same issue. I was downloading my list of claimed books. One of them has code/zip file of about 900MB and it times out.

**Comment by trancen** [comment]
@nevzat  I added a progress bar code, see my fork, I have also submitted the code back to igbt6. It also resolves the issue where it times out on the download. I downloaded a 900mb file without a issue.

**Comment by nevzat** [comment]
Many thanks.

**Comment by igbt6** [comment]
Good job! Can you open a pull request, i would merge your changes to the main branch if you don't mind : )
