### ISSUE TITLE
Escape slashes ("/") from book titles

### ISSUE THREAD

**Issue by djvdorp** [igbt6/Packt-Publishing-Free-Learning#2]
The slash ("/") is mistaken for a path separator on Unix, see example issue here:

```
downloading eBook: 'Oracle Advanced PL/SQL Developer Professional Guide' in '.pdf' format...
[ERROR] - Exception occured durin opening file [Errno 2] No such file or directory: '/home/daniel/myEbooksFromPackt/OracleAdvancedPl/sqlDeveloperProfessionalGuide.pdf'
--done--
```

**Comment by igbt6** [comment]
thanks, fixed

**Comment by djvdorp** [comment]
Thanks! I think the other slash ("\") might also be a problem but then on Windows, but not sure about that.

**Comment by igbt6** [comment]
yes, you are right, i should be fixed as well for windows. Forgot about it.
