### ISSUE TITLE
Running on docker containers

### ISSUE THREAD

**Issue by astondevops** [igbt6/Packt-Publishing-Free-Learning#20]
First of all, thanks for your code it works fine on my localhost but I've got something strange when moving your code in a docker container  on a KVM VM.
So I have a small VM from Lunanode in Roubaix and set up a docker container using a docker build with all your code on python3.4. 
All is good till I got a trouble in line 177 of your Pack py program. I have a 404 error but I don't why the beautifulsoup parser find the downloaded url but failed afterwards for some reason but all works on my localhost. Did I miss something when moving to a container? 
Thanks

**Comment by igbt6** [comment]
Hello, honestly i have no idea what kind of a problem it might be, try to debug it deeper and share your solution when you are done,
Thanks in advance,

BR,
łukasz
