### ISSUE TITLE
'flush' error when using Python 2 from the progress bar

### ISSUE THREAD

**Issue by teekay30** [igbt6/Packt-Publishing-Free-Learning#25]
[ERROR] - 'flush' is an invalid keyword argument for this function

I believe it's because Python 2 doesn't support the use of 'flush=true' as it's a feature starting from Python 3.3 from what I gather.
Line 215 from : 
` print("\r[PROGRESS] - [{0:50s}] {1:.1f}% ".format('#' * int(currentWorkDone * 50), currentWorkDone*100), end="", **flush=True**)`
Alternative to this would be to 'import sys' and then to flush it manually in a separate line:
`sys.stdout.flush()`

Doesn't affect the functionality of the script itself but the progress bar will not be shown when using Python 2. It seems like the above is also supported in Python3, obviously not as nice as having it as an argument to print() though.
Btw love the script, nice work on it :+1:

**Comment by igbt6** [comment]
good find, yeah i actually missed testing it with python 2, I will fix it soon
Best regards!

**Comment by igbt6** [comment]
As Packt renewed their free books daily offer, i have fixed it : )
