### ISSUE TITLE
windows line endings in `packtPublishingFreeEbook.py`

### ISSUE THREAD

**Issue by troyp** [igbt6/Packt-Publishing-Free-Learning#34]
The python file is contaminated with windows line endings. As a result, if you execute this file directly (via the shebang), an error occurs since the shell can't find "python\r". The line endings can be converted (eg. with `dos2unix`), but that puts the repo out-of-sync. It's not a problem if you execute with `python packtPublishingFreeEbook.py`.

__to reproduce:__ On unix, clone repository and execute:

    cd Packt-Publishing-Free-Learning
    chmod a+x packtPublishingFreeEbook.py
    ./packtPublishingFreeEbook.py

__exprected result:__ script should run, outputting `[INFO] - Creating session...` , etc.
__actual result:__  script aborts with error: `/usr/bin/env: ‘python\r’: No such file or directory`

**Comment by igbt6** [comment]
already fixed on master, chek this out!
