### ISSUE TITLE
Feature request: grab a book and send email about success/failure

### ISSUE THREAD

**Issue by mjenczmyk** [igbt6/Packt-Publishing-Free-Learning#42]
First of all - thanks, your script is saving me a few minutes every day.

Now I'm thinking about running this script on [PythonAnywhere](https://www.pythonanywhere.com/) as a scheduled task and what I miss is a possibility to grab a book and send me an email whether script execution was successful. I've seen there are two similar features - to grab a book and log it into file and another one allowing to grab a book and email it to me.

I could try to fork your repo and implement such feature - would you consider accepting such pull request?

Have a good day,
Marcin

**Comment by igbt6** [comment]
Cześć Marcin!
Actually yeah i have been using similar notification on my webserver, which informs me when by sending email when the script has failed, i have jsut added it to main repo , take a look on -rm option. 
Best regards!

**Comment by mjenczmyk** [comment]
Cześć!

Actually I was thinking about something a bit different - I would send an email even if script has succeeded - in case of hosting service failure, problems with the internet connection I wouldn't know about failure because I wouldn't receive any email informing me about failure; I wouldn't be able to distinguish situations when everything went well and when sending an email about failure failed.

On the other hand, if I expected an email informing me about success or failure that would be entirely different situation - lack of email received would be alarming.

**Comment by igbt6** [comment]
yeah, seems reasonable, so  maybe the easiest solution would be just use the same option flag "-rm" and move the code on success as well:
`        if args.report_mail:
            from utils.mail import MailBook
            mb = MailBook(cfgFilePath)
            mb.send_info(body="messgae on success")   
 `
Propose some changes, i'll merge it then,
Regards!

**Comment by mjenczmyk** [comment]
OK, I'll try to do that in the evening.

This parameter shorthand `-rm` is very creepy to me :D

**Comment by igbt6** [comment]
-rm as [--report_mail], feel free to modify

**Comment by mjenczmyk** [comment]
That's fine, it just recalls `rm` command which can be destructive.

**Comment by igbt6** [comment]
done
