### ISSUE TITLE
upload already downloaded files to google drive

### ISSUE THREAD

**Issue by katonap** [igbt6/Packt-Publishing-Free-Learning#52]
Is it possible to upload the already downloaded files/folders to google drive in a way that the folder structure of the google drive upload folder would be the same as the structure of the download_folder_path?

**Comment by igbt6** [comment]
yeah sure, it should work, just create:
`                google_drive = GoogleDriveManager(cfg_file_path)
                google_drive.send_files(paths)
`
where `paths are` all book paths and `cfg_file_path` is the .cfg file location which contains root_folder name

**Comment by katonap** [comment]
Thanks, I tweaked it a little here and there and it works like a charm
