### ISSUE TITLE
Download the last one, two or X claimed books

### ISSUE THREAD

**Issue by yodous** [igbt6/Packt-Publishing-Free-Learning#54]
Hello,
While the option to automatically grab a book is not available right now (Captcha), please consider include option to download the last X books from the all books list.
The is an option to download all books. The latest claimed books are at the top of the list, so it should be easy to just pick the one, two or X last claimed books.
It will do some of the work, while I have to manually claim the book, I could run the script to automatically download it and move to some directory / send to google.

Best Regards
Y

**Comment by eharris** [comment]
+1 for this.  At the moment I have a weekly cron invocation that downloads all books, but I'd prefer to have it download the current book automatically as long as I've already claimed it.

**Comment by josevill** [comment]
Thing is the books aren't arranged by date but by names.
So we'd have to make a list of all grabbed books and make a new param.

**Comment by eharris** [comment]
I don't think that's true.  I've noticed that the list of ebooks on your account is ordered in reverse-chronological order of acquisition.  The link is here:

https://www.packtpub.com/account/my-ebooks

So that page can be used to easily find and fetch the last N books purchased by just processing them in the order they are displayed on that page.

**Comment by josevill** [comment]
I'll have to double-check that one, last time mine was arranged by letters,
might've been a simple coincidence.

If it's ordered by acquisition date, it's going to be easy to make it
possible.

2017-07-03 23:27 GMT+02:00 Evan Harris <notifications@github.com>:

**Comment by yodous** [comment]
At the moment I'm using below JS script on site https://www.packtpub.com/account/my-ebooks to get the string, which I'm putting into configFile for: downloadBookTitles

```
var arrText = [];
jQuery('div.title:lt(10)').each(function (ix, el) {
	arrText[ix] = $(el).text().replace("[eBook]", "").trim();
});
console.log(arrText.join(", "));
```

**Comment by mjenczmyk** [comment]
The order date is provided inside the `div`s with books in your collection on https://www.packtpub.com/account/my-ebooks, so one could easily extract it and add as a new entry key the list of all books that is created in `BookDownloader.get_my_all_books_data`.

What you are writing about shouldn't be hard to achieve, one could even add a command that downloads all books ordered between two given dates.

**Comment by mjenczmyk** [comment]
How about downloading books grabbed between two given names?

**Comment by igbt6** [comment]
Rejected by the same reason as at #59, I think that downloading by ebook's title is enough and keeps the code simple and clean for everyone
