### ISSUE TITLE
Captcha?

### ISSUE THREAD

**Issue by woeterman94** [igbt6/Packt-Publishing-Free-Learning#55]
How can we get this to work with the captcha?

Kr

**Comment by Santosh-Sah** [comment]
They have removed the captcha verification now

**Comment by Palatosino** [comment]
They don't removed the captcha verification. They moved to no-captcha reCaptcha. Yo can see the reCaptcha logo in the corner of the web.

**Comment by Santosh-Sah** [comment]
Yeah I have inspected the page and found they are using google re-captcha invisible

**Comment by woeterman94** [comment]
Why is this closed? Doesn't seem resolved to me

**Comment by ad-m** [comment]
@woeterman94 , fixed in #56 .
