### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by mjenczmyk** [igbt6/Packt-Publishing-Free-Learning#68]
Last Python 2.6 release was in 2008. Could we drop the support for it and remove redundant code?

**Comment by igbt6** [comment]
feel free to open a PR, btw why do you open such question as an issue ?? It's a PR question.  Closed

**Comment by mjenczmyk** [comment]
I just don't want to make a work that'll be rejected - there is a chance that changes that require decision will be rejected when the PR is made. 

But OK, I'll do this when I'll have a moment.

**Comment by igbt6** [comment]
Ok, you are right! It sounds reasonable : ) 
Regards!
