### ISSUE TITLE
problem with attribute

### ISSUE THREAD

**Issue by dotweb** [igbt6/Packt-Publishing-Free-Learning#7]
During excecutions python packtPublishingFreeEbook.py -da
[INFO] - Creates session ...
[INFO] - Session created, logged succesfully!
[INFO] - Getting data of all your books...
[INFO] - opened  'https://www.packtpub.com/account/my-ebooks' succesfully!
[ERROR] - Exception occured 'NoneType' object has no attribute 'find_all'

**Comment by igbt6** [comment]
could you provide some more details when it happens ? what os, python version. etc ?

**Comment by dotweb** [comment]
I'am sorry, I am on Ubuntu 16.04, pyhton -version 2.7.  It's success until logged on. but error some how. also the other option [-g], errors code like;
[INFO] - Creates session ...
[INFO] - Session created, logged succesfully!
[INFO] - start grabbing eBook...
[ERROR] - Exception occured eBook:R Machine Learning Essentials has not been grabbed~! ,http GET status code != 200

**Comment by igbt6** [comment]
Nobody has found such issue so far, maybe u've been using any proxy ? , im closing it for now.
