### ISSUE TITLE
apiclient has no http module

### ISSUE THREAD

**Issue by mjenczmyk** [igbt6/Packt-Publishing-Free-Learning#72]
When i try to import from `apiclient.http` i get `ImportError`. That's what we do in Google Drive module. I guess we should import from [Google API Python Client](https://google.github.io/google-api-python-client/docs/epy/googleapiclient.http-module.html), but I started to wonder if Google Drive integration was ever working? @igbt6, have you ever used it?

I can make a pull request to use Google API Python Client, but I won't be able to see if entire functionality works (I don't use Google services). Should I make a pull request in that case? Will anybody fix/use that functionality?

```python
>>> from apiclient.http import MediaFileUpload
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named http
```

**Comment by igbt6** [comment]
@mjenczmyk I am using it on my daily basis and works like a charm, maybe some changes occured in the API somehow recently, i will check it

**Comment by igbt6** [comment]
Tested, works correctly for python 3.6 and 2.7

**Comment by mjenczmyk** [comment]
Thanks, I've seen that Google API Python Client has replaced apiclient in requirements.txt.
