### ISSUE TITLE
usage with Anaconda

### ISSUE THREAD

**Issue by nevzat** [igbt6/Packt-Publishing-Free-Learning#76]
I uninstalled pure Python on my Windows system and switched to use Anaconda. How should I install this script and its requirements? conda or pip? I created a new environment for just this script but don't know / can't decide what to do now. Can someone add some help to instructions on installing this under Anaconda please?

**Comment by igbt6** [comment]
Hello, I think there is no need to add any instructions  for Anaconda envs. As stated:  "Both pip and conda are included in Anaconda and Miniconda, so you do not need to install them separately". Just use pip and it should work : )
https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages

**Comment by nevzat** [comment]
Thank you. I tried installing with pip and succeeded!
