### ISSUE TITLE
Website stoken 'Array' is invalid.!

### ISSUE THREAD

**Issue by rivabem** [igbt6/Packt-Publishing-Free-Learning#79]
Grabber is failing for 4 easy with the message below, no change in my environment, maybe in packt's:

Today's free Packt ebook grabbing has failed with exception: Some of the required values for successive user emulation are missing.. Website stoken 'Array' is invalid.!

**Comment by rivabem** [comment]
Typo: it has failed 4 days already.

**Comment by ad-m** [comment]
This is a change that was introduced in Anti-captcha.com API. Fixed in ad-m/python-anticaptcha#4 three days ago. Use ```pip install python-anticaptcha -U``` or update this app.

**Comment by rivabem** [comment]
Used pip. Solved!
Thanks.
