### ISSUE TITLE
feature request : download last x number of claimed e-books

### ISSUE THREAD

**Issue by nevzat** [igbt6/Packt-Publishing-Free-Learning#8]
Could you add a parameter so that we can download last "x" number of claimed e-books? (e.g. last 10 claimed e-books)

I'm a Python newbie, I couldn't do it.

Thanks

**Comment by igbt6** [comment]
hello! 
I think such feature is not very needed or even convenient to use.  The books are already being downloaded in such order (from last claimed to the oldest ones) If you really need this you can easily check when **nrOfBooksDownloaded**  variable is bigger than 10, then finish it. Best regards!

**Comment by nevzat** [comment]
I didn't know that variable exists. That should do the trick. Thanks.
