### ISSUE TITLE
Error no module named requests

### ISSUE THREAD

**Issue by huczas** [igbt6/Packt-Publishing-Free-Learning#89]
RaspberryPi3 -all upgraded, Python 3.6.0
When firedup from crontab I get this:
packtPublishingFreeEbook.log:
```Traceback (most recent call last):
  File "packtPublishingFreeEbook.py", line 13, in <module>
    import requests
ImportError: No module named 'requests' 
```

I maked venv for packtpub and installed inside venv all from file requirements.txt 
```
pip3 install requests==2.18.4
Requirement already satisfied: requests==2.18.4 in /home/pi/packtpub/lib/python3.6/site-packages```

**Comment by ad-m** [comment]
Invalid python executable. Use in cron python executable from virtualenv.

**Comment by huczas** [comment]
Thanks for that tip- works ok now.
