### ISSUE TITLE
feature request : save to google drive

### ISSUE THREAD

**Issue by nevzat** [igbt6/Packt-Publishing-Free-Learning#9]
I think it's possible via Google Apps Script's Python extensions I found on this page : https://developers.google.com/apps-script/guides/rest/quickstart/python

It would be great to save the e-books to a predefined folder on our Google Drive storage, by giving our Google credentials in cfg file.

**Comment by igbt6** [comment]
Hello, it's a good idea. I have already written a python script that synchronizes folders from my PC with  Google Drive (makes a copy of them).  [Here are the sources](https://github.com/igbt6/GoogleDriveFileSynchronizer)  So maybe i'll find somne time to add it to this cript

**Comment by nevzat** [comment]
I'm still learning Python. I hope I can contribute my first GitHub codes with this project. Cheers.

**Comment by igbt6** [comment]
done
