### ISSUE TITLE
[ERROR] - Exception occurred eBook: Practical_Mobile_Forensics has not been grabbed!, does this promo exist yet? visit the page and check!

### ISSUE THREAD

**Issue by ranrinc** [igbt6/Packt-Publishing-Free-Learning#90]
This happen today, so to be sure I double check and manually have to download the books. Its seems that upon login packt is sending us to a different pages making the download fail.

**Comment by mjenczmyk** [comment]
It failed for me that day also, there were some problems and the Packt website was down. Later when I checked the book was grabbed anyway, do you have this book in your collection?

Up to the 1st January there will be no free learning books (so don't worry if your script fails).
