### ISSUE TITLE
is there away to download books that have not being sync

### ISSUE THREAD

**Issue by ranrinc** [igbt6/Packt-Publishing-Free-Learning#92]
Is there away to download the books that already in my download list that have not being sync to my google drive? The reason because from time-to-time captcha fail and the books have to be downloa manually. So I left with a lots book unupdated to google drive.

**Comment by ad-m** [comment]
I do not download books bypassing the script. In case of problems, I run the script again. The fee is charged for the correct captcha solution, so it does not cost extra. You can automate restarting for a while.

**Comment by mjenczmyk** [comment]
@ranrinc Does that help? Can the issue be closed?

**Comment by igbt6** [comment]
Workaround proposed
