### ISSUE TITLE
Download list of all ebook on account

### ISSUE THREAD

**Issue by AlessioC** [igbt6/Packt-Publishing-Free-Learning#95]
Hi! There are some possibilities that you can implement a way to download a complete .txt list wit all e-books inside the logged account?

Thanks in advance

**Comment by igbt6** [comment]
No plan for such feature, but hey it's should be very easy and quick task, maybe try to do it yourself ? 
I can always help : )

**Comment by AlessioC** [comment]
I'm a novice with python but ok, I'll try! In case, I'll demand your help :P

**Comment by AlessioC** [comment]
I did it! I added a few lines to _get_my_all_books_data
`def __get_my_all_books_data(self):
        """Gets data from all available ebooks"""
        logger.info("Getting data of all your books...")
        r = self.session.get(self.cfg.my_books_url, timeout=10)
        if r.status_code is not 200:
            message = "Cannot open {}, http GET status code != 200".format(self.cfg.my_books_url)
            logger.error(message)
            raise requests.exceptions.RequestException(message)
        logger.info("Opened '{}' successfully!".format(self.cfg.my_books_url))
        self.book_data = []
        my_books_html = BeautifulSoup(r.text, 'html.parser')
        all = my_books_html.find_all('div', {'class': 'product-line'})
        f = open("list.txt", "a")
        for line in all:
            if not line.get('nid'):
                continue
            title = line.find('div', {'class': 'title'}).getText().strip(' ').replace(' [eBook]', '')
            f.write(title.encode('utf8'))
            download_urls = {}
            for a in line.find_all('a'):
                url = a.get('href')
                for fm in self.download_formats:
                    if url.find(fm) != -1:
                        download_urls[fm] = url                      
            self.book_data.append({'title': title, 'download_urls': download_urls}) 
        f.close()`

**Comment by AlessioC** [comment]
I did it! I added a few lines to _get_my_all_books_data
```
def __get_my_all_books_data(self):
        """Gets data from all available ebooks"""
        logger.info("Getting data of all your books...")
        r = self.session.get(self.cfg.my_books_url, timeout=10)
        if r.status_code is not 200:
            message = "Cannot open {}, http GET status code != 200".format(self.cfg.my_books_url)
            logger.error(message)
            raise requests.exceptions.RequestException(message)
        logger.info("Opened '{}' successfully!".format(self.cfg.my_books_url))
        self.book_data = []
        my_books_html = BeautifulSoup(r.text, 'html.parser')
        all = my_books_html.find_all('div', {'class': 'product-line'})
        f = open("list.txt", "a") #1
        for line in all:
            if not line.get('nid'):
                continue
            title = line.find('div', {'class': 'title'}).getText().strip(' ').replace(' [eBook]', '')
            title2=title.strip()+"\n" #2
            f.write(title2.encode('utf8')) #3
            download_urls = {}
            for a in line.find_all('a'):
                url = a.get('href')
                for fm in self.download_formats:
                    if url.find(fm) != -1:
                        download_urls[fm] = url                      
            self.book_data.append({'title': title, 'download_urls': download_urls}) 
        f.close() #4

```
it works with -dc argument
