### ISSUE TITLE
Error downloading...

### ISSUE THREAD

**Issue by ranrinc** [igbt6/Packt-Publishing-Free-Learning#96]
Unsure what happen. However today the books have not being able to downloaded and the script stop functioning (not being able to find the books) 

Double check and the books do available and doing it manually it go into my download list.

<img width="568" alt="screen shot 2018-03-04 at 4 22 18 pm" src="https://user-images.githubusercontent.com/15801696/36944133-844dc4ec-1fc8-11e8-9684-a4fae6a8fdce.png">

**Comment by ad-m** [comment]
Fortunately, claiming works correctly.

**Comment by mjenczmyk** [comment]
Do we know how to reproduce that error? It seems the Packt website listing books just didn't note you have already grabbed the book, the issue could be closed IMO if @ranrinc does not mind.

**Comment by igbt6** [comment]
Closed as not reproducible
