### ISSUE TITLE
Abbility to download the Info and Cover Of the Book

### ISSUE THREAD

**Issue by RuthlessRuler** [igbt6/Packt-Publishing-Free-Learning#97]
I tried putting the argument of downloading the cover and info, but the script ignores it. 
This is how my download data looks:

[DOWNLOAD_DATA]
download_folder_path: C:\Users\kunal\Downloads\Compressed\PAckt
download_formats: pdf, epub, mobi, cover, code, info
download_book_titles: Unity 4.x Game AI Programming , Multithreading in C# 5.0 Cookbook 
ebook_extra_info_log_file_path: eBookMetadata.log

**Comment by RuthlessRuler** [comment]
Also, the ability to download the Ebooks after one particular ebook will be Actually Really Helpful. 
Like if i downloaded till 60th ebook from my account, then the ability to download from the 61th ebook will be great.

**Comment by mjenczmyk** [comment]
There is no possibility to download cover or info right now - it's no surprise it doesn't work. Why did you expect that putting cover and info under download_formats key would work?

According to your second question - when you have some books downloaded the script will skip them in subsequent downloads as long as they are still there in download directory.

Does this help?

**Comment by RuthlessRuler** [comment]
Well, one of the other scripts 8 was using had that features so I thought maybe this script too had that feature. But that script required 2.7.x and didn't work well with version I had installed.

Also, for the second question, I meant, what if I deleted the files previously downloaded but wanted to start from a particular book, is that possible nor maybe can you add that feature too.

**Comment by mjenczmyk** [comment]
OK, I see. Out of curiosity - what was the script, can I see the code somewhere?

I cannot see the how the case of downloading from nth book should work, but I also could never understand how downloading books by name is useful. I was thinking about implementing downloading books grabbed between two given dates - would that cover your needs?

**Comment by RuthlessRuler** [comment]
The repository can be found here:- https://github.com/ozzieperez/packtpub-library-downloader

Also, since the program starts downloading books with the latest claimed as 1st, so why not sort of add some counter that will count the books from that point to the last book. So, if I downloaded till 60th book, moved/deleted them, and then I want to resume downloading from 61th book is a way I think this can be achieved.

Also, the idea of using dates is also good. I guess that will work too.

**Comment by igbt6** [comment]
Too many possibilities = bigger mess and more work to keep it working, when page will change in future.
Such features you can implement on your own, what i do really recommend  :)

**Comment by mjenczmyk** [comment]
Interesting, I consider `-dc` option too specific as well and obsolete - it's easier for me to log into Packt account and download ebook manually than put ebook's name into config file.

**Comment by igbt6** [comment]
You're right, I don't think anyone is using it ;)

**Comment by mjenczmyk** [comment]
Should I remove it? I don't wanna be too destructive, so let me know if I'm too eager ;)

**Comment by RuthlessRuler** [comment]
Yeah, I don't think anyone will us that, they in the end will have to copy name of each titles, so most will directly download it.

Also, please do implement -dr(download range) I future.

**Comment by mjenczmyk** [comment]
https://github.com/igbt6/Packt-Publishing-Free-Learning/pull/101

**Comment by mjenczmyk** [comment]
Should we close that issue?
